//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsieAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripUser
    {
        public TripUser()
        {
            this.ActivityVotes = new HashSet<ActivityVote>();
            this.PushRegistrations = new HashSet<PushRegistration>();
            this.TripComments = new HashSet<TripComment>();
            this.TripPictures = new HashSet<TripPicture>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TripId { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsCreator { get; set; }
        public string TripCode { get; set; }
        public int TripStatus { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
    
        public virtual ICollection<ActivityVote> ActivityVotes { get; set; }
        public virtual ICollection<PushRegistration> PushRegistrations { get; set; }
        public virtual ICollection<TripComment> TripComments { get; set; }
        public virtual ICollection<TripPicture> TripPictures { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
