//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsieAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public Trip()
        {
            this.TripActivities = new HashSet<TripActivity>();
            this.TripUsers = new HashSet<TripUser>();
        }
    
        public int Id { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string Code { get; set; }
        public string Destination { get; set; }
        public string Description { get; set; }
        public string MyName { get; set; }
        public string UserJson { get; set; }
        public int Status { get; set; }
    
        public virtual ICollection<TripActivity> TripActivities { get; set; }
        public virtual ICollection<TripUser> TripUsers { get; set; }
    }
}
