//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsieAppWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripActivity
    {
        public TripActivity()
        {
            this.ActivityVotes = new HashSet<ActivityVote>();
        }
    
        public int Id { get; set; }
        public string Activity { get; set; }
        public string Details { get; set; }
        public int TripId { get; set; }
        public int TripUserId { get; set; }
        public long Lat { get; set; }
        public long Lon { get; set; }
        public bool IsComplete { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<ActivityVote> ActivityVotes { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
