//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TripsieAppWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TripAppEntities : DbContext
    {
        public TripAppEntities()
            : base("name=TripAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ActivityVote> ActivityVotes { get; set; }
        public virtual DbSet<PushRegistration> PushRegistrations { get; set; }
        public virtual DbSet<TripActivity> TripActivities { get; set; }
        public virtual DbSet<TripComment> TripComments { get; set; }
        public virtual DbSet<TripPicture> TripPictures { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripUser> TripUsers { get; set; }
    }
}
